### ISSUE TITLE
Is it usable as-is?

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam-raycast#1]
Hi!
Being a Raycast user myself I am quite interested in seeing how the 2 could integrate.

I created my first tiny sunbeam extension and wanted to see if I could use it in Raycast as well but after installing the extension locally, I just get the 2 following options:
![image](https://github.com/pomdtr/sunbeam-raycast/assets/8754100/74e3be99-e8e1-473c-92a4-2d39ac6e0edb)

Is the intent that all sunbeam extensions will be available in Raycast?

**Comment by pomdtr** [comment]
The raycast extension used to launch a process to execute sunbeam, but I'm experimenting with another design. 

Instead of requiring sunbeam to be installed, the raycast extension is now a sunbeam client, that talks with a sunbeam server. A server is any endpoint returning a json respecting the sunbeam schema. 

I plan to add a server mode to the sunbeam binary (that would transform any sunbeam extension to json server), but in the meantime I mostly use the extension by combining it with val.town.

At some point I'll built a mobile app with this design.

**Comment by pomdtr** [comment]
it should be supported now

**Comment by b-per** [comment]
Excited to try it! I am facing some issues but I will raise them separately
